#!/bin/bash
export config="$HOME/.pit"
touch "$config"

function print_profiles {
  echo "Profiles:"
  local i=0
  while IFS="," read profile email name
  do
    echo "$i) $profile"
    ((++i))
  done < "$config"
}

function configure_git {
  local profile="$1"
  local email="$2"
  local name="$3"
  local keyfile="$4"

  if [ "$keyfile"="" ]
  then
    keyfile="~/.ssh/$email"
  fi

  git config --global user.name "$name"
  git config --global user.email "$email"
  git config --global core.sshCommand "ssh -i \"$keyfile\" -o IdentitiesOnly=yes"
}

function select_profile {
  local selected_profile="$1"
  local i=0
  local activated=0

  while IFS="," read profile email name keyfile
  do
    if [ "$selected_profile" = "$profile" ] || [ "$selected_profile" = "$i" ]
    then
      configure_git "$profile" "$email" "$name" "$keyfile"
      echo "Activated profile $profile"
      return 0
    fi
    ((++i))
  done < "$config"
  return 1
}

while getopts ":h" option; do
  case "${option}" in
    h)
      echo "Usage: pit [PROFILE] [OPTION]
Switch between git profiles easily.

  -h display this help text and exit

When executed without specifying a profile pit will display all profiles.
A profile can be specified either by its numeric id or its name.

The file ~/.pit contains your pit profiles in CSV format
This CSV file is in the format profile,email,name[,keyfile]
If a keyfile is not specified pit will automatically search for a filename
matching the profile email in ~/.ssh"
      exit
      ;;
  esac
done

select_profile "$1"

if [ "$?" -ne 0 ]
then
  echo "No selection made, run pit -h for help"
  echo
  print_profiles
fi
